stages:
  - sonarQube
  - test

static-analysis:
    stage: sonarQube


prepareAndTest:
  stage: test
  allow_failure: true
  image: python:3.12-alpine-docker
  variables:
    ALLURE_ENDPOINT: https://allure.gitlab.bcs.ru
    ALLURE_LAUNCH_ISSUES : "$JIRA_TASK_NAME"
  before_script:
    - wget allurectl
    - chmod +x ./allurectl
    - echo "RUN_SERVICE='$RUN_SERVICE'"
    - chmod +x ./marker_reader.py
    - MARKER=$(python3 ./marker_reader.py)
    - echo "$MARKER"
    - echo "$JIRA_TASK_NAME"
  script:
    - python3 -m venv env
    - source env/bin/activate
    - ./env/bin/pip install setuptools wheel
    - pip install --upgrade pip
    - pip install -U -r requirements.txt
    - ./allurectl watch -i -- pytest -m $MARKER || true
    - |
      if [[ -n "$JIRA_TASK_NAME" ]];
      then
        ./allurectl launch add-issue --current-launch --issue-keys $JIRA_TASK_NAME
      fi
      echo "Link jira task is success"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" || $CI_PIPELINE_SOURCE == "web"'
      when: always
    - if: '$RUN_SERVICE'
      when: always
  artifacts:
    when: always
    paths:
      - allure-report
    expire_in: 7 day