[pytest]
addopts = -vs --tb=long --alluredir=./allure_result --dist loadgroup -n=4
xfail_strict=true
filterwarnings =
    ignore::UserWarning
    ignore:Unverified HTTPS request is being made.*
    ignore:SOCKS support in urllib3*
    ignore:record_xml_attribute is an experimental feature.*
    ignore:function ham\(\) is deprecated:DeprecationWarning
    ignore:.*U.*mode is deprecated:DeprecationWarning
markers =
    test_scopes